### ISSUE TITLE
Nemo desktop support

### ISSUE THREAD

**Issue by siren15** [Tommimon/add-to-desktop#30] opened 2023-12-31 17:46 UTC
Hi, I was wondering if this extension supports nemo-desktop. I saw nemo being mentioned in issue #9, and I was thinking if it does support it or if it's broken, since I can't see `add to desktop` option in either arcmenu or the original gnome menu, when using nemo desktop, instead of ding extension.

I'm on Nobara 39 using Gnome 45 and with this extensions version 11 installed trough gnome extensions website.

**Comment by Tommimon** [comment] 2024-01-02 00:10
I didn't test it with arcmenu but if it uses custom widgets to display icons there is nothing we can do about it and it will probably never be compatible.

That said, the option should be available in the vanilla GNOME application menu, I never used Nemo but I don't see how the file manager or the desktop could interfere with the application menu.

If I'm going to try to reproduce this I'm interested in what is exactly the breaking point.

Do you have a setup that works with the vanilla GNOME? What is exactly the action that breaks it? Is it removing Nautilus? Is it installing Nemo? Is it the installation of any other extension?

**Comment by siren15** [comment] 2024-01-07 22:37
Hi, thank you for responding. Since I no longer had a clean gnome install set up after I wrote that due to my system breaking. I had to set up a VM with clean Fedora 39, and there it did work with nemo desktop and the GNOME app menu, but didn't with arcmenu unfortunately. In the end it might've been that my gnome install was corrupt in some way at the time, and broke it in the gnome menu as well.

**Comment by Tommimon** [comment] 2024-02-23 13:29
Since the main topic of this issue was Nemo compatibility, and it works, I think we can close this.

**Closed by Tommimon** 2024-02-23 13:29 UTC
